package no_16_advanced2_java;

public class no_089_javadocs {

    public static void main(String[] args) {
        
    }
}


/* 
    ---------->> CREATING OUR OWN JAVA DOCUMENTATION ..
    - JAVA DOCUMENTATION IS GRATE .. 
    IT HELP US TO GET INFO ABOUT WHICH METHOD / CLASS / ENTITY TO USE WHEN ,
    WE CAN CREATE OUR PACKAGES DOCUMENTATION IN JAVA 

------ JAVA DOC TOOL 
JAVA DOC COMMAND ALLOW US TO CREATE DOCUMENTATION IN HTML FORMAT FOR OUR PACKAGE..
- JAVA PROVIDE TAGS FOR CLASS OR PACKAGE TO ASSIST WITH JAVA DOC GENERATION 

------ TAGS FOR CLASS OR A PACKAGE 

1.  author  :  ADD THE AUTHOR NAME 
2.  version : ADDS THE VERSION
3.  since :   TO ADD WHEN WAS THIS VERSION WRITTEN 
4.  see :   ADDS A SEE ALSO HEADING WITH A LINK 

------ TAGS FOR MRTHODS

1.  param :  FOR DESCRIBING PARAMETERS OF METHODS 
2.  return : FOR DESCRIBING ABOUT THE RETURN VALUE
3.  throws : FOR DESCRIBING EXCEPTION THROWS   
4.  deprecated :  FOR DESCRIBING DEPRECATED STATUS   






*/