package no_15_advanced_java_1;

//import java.util.ArrayList;         // JAVA FRAMEWORK-COLLECTIONS ARE PRESENT IN java.util PACKAGE 

public class no_76_collections {
    public static void main(String[] args) {
        // ArrayList



    }
}


/* 
--------->> COLLECTIONS FRAMEWORK    
A COLLECTION REPRESENTS GROUP OF OBJECT.. JAVA COLLECTION PROVIDED CLASSES AND INTERFACES FOR US TO BE ABLE TO WRITE 
CODE QUICKLY AND EFFICIENTLY..

WHY DO WE NEED COLLECTIONS ?? 
WE NEED COLLECTIONS FOR EFFICIENT STORAGE AND BETTER MANUPULATION OF DATA IN JAVA..

FOR EG - WE USE ARRAYS TO STORES INTEGERS BUT WHAT IF WE WANT TO : 
● RESIZE THE ARRAY ?
● DELETE AN ELEMENT IN ARRAY ?
● APPLY CERTAIN OPERATIONS TO CHANGE THIS ARRAY 

COLLECTIONS CLASS IS AVAILABLE IN java.util PACKAGE.. COLLECTION CLASS ALSO PROVIDES STATIC METHOD 
FOR SEARCHING , SORTING ... etc 

HOW COLLECTIONS ARE AVAILABLE ??
- COLLECTIONS IN JAVA ARE AVAILABLE AS CLASSES AND INTERFACES FOLLOWING ARE FEW COMMONLY USE COLLECTIONS IN JAVA :

- ArrayList - FOR VARIABLE SIZE COLLECTION
- set  - FOR DISTINCT COLLECTIONS
- stack - A LIFO (LAST IN FIRST OUT) DATA STRUCTURE
- HashMap - FOR STORING KEY-VALUE PAIRS 



NOTE : LinkedList , ArrayList , ArrayDeque , Hashing , HAshSet ARE THE DATASTRUCTURES AND ALGORITHMS TOPICS..
        SO, WE DONT'T STUDY THEM IN DEPTH.. 


*/